      PROGRAM DRVBET
      INCLUDE 'PRGPRM.F77'
      INCLUDE 'PPEPRM.F77'
      INCLUDE 'BMPRM.F77'
      INCLUDE 'CONTRL.F77'
      INCLUDE 'BMCOM.F77'
      REAL BETA(NSCL), ABETA
      INTEGER I
      LBMDEB=.FALSE.
      ABETA=2.5
      CALL BMCBET(ABETA, 1, 8, BETA)
      DO 10 I=1,NSCL
        WRITE(*,'(A,I2,1X,Z8.8)') 'B',I,BETA(I)
   10 CONTINUE
      END
