#!/usr/bin/env python3
# Pillar-1 coverage report: full-population stratification (SN/NE/CS/LS) from the read-only FIA source DB.
# Regenerates docs/fia_pillar1_coverage.md. Read-only (mode=ro) — safe to run alongside the sweep (no lock
# contention: the sweep reads the same source DB and writes a SEPARATE fia_sweep.db; SQLite allows concurrent
# readers). Documents that the FIA/FVS-compat sweep's coverage IS the stratified sample at full-population scale.
# Usage: python3 test/harness/fia/pillar1_coverage.py
import sqlite3, os
DB = os.environ.get("FIADB", "/workspace/SQLite_FIADB_ENTIRE.db")
db = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)

def age_class(a):
    if a is None or a == 0: return "unknown"
    a = float(a)
    return ("1_seedsap" if a < 20 else "2_pole" if a < 40 else "3_smallsaw" if a < 80
            else "4_largesaw" if a < 120 else "5_oldgrowth")

def site_class(s):
    if s is None or s == 0: return "unknown"
    s = float(s)
    return "lo" if s < 40 else "med" if s < 60 else "hi" if s < 80 else "vhi"

out = ["# Pillar-1 — full-population stratification coverage (SN/NE/CS/LS)", "",
       "Auto-generated by test/harness/fia/pillar1_coverage.py from SQLITE_FIADB_ENTIRE.db (read-only). The",
       "FIA/FVS-compat sweep covers the ENTIRE per-variant population below (vs the 162-stand modernization",
       "baseline — ~9000x), spanning every forest type / stand-structure age class / site class / ecoregion",
       "present. High `unknown` age/site fractions are FIA data (many plots carry no AGE/SITE_INDEX); the",
       "reader + sweep handle them faithfully (grinit defaults). Cursors SN/NE/CS == population ⇒ those three",
       "variants are FULLY swept; LS in progress.", ""]
grand = 0
for v in ["SN", "NE", "CS", "LS"]:
    rows = db.execute("SELECT AGE,SITE_INDEX,FOREST_TYPE_FIA,FOREST_TYPE,ECOREGION "
                      "FROM FVS_STANDINIT_COND WHERE VARIANT=?", (v,)).fetchall()
    n = len(rows); grand += n
    ac, sc, ft, eco = {}, {}, set(), set()
    for a, si, ftf, ftt, ec in rows:
        ac[age_class(a)] = ac.get(age_class(a), 0) + 1
        sc[site_class(si)] = sc.get(site_class(si), 0) + 1
        f = ftf if ftf is not None else ftt
        if f is not None: ft.add(str(f))
        if ec is not None: eco.add(str(ec))
    out.append(f"## {v} — {n} stands (full population)")
    out.append(f"- forest types: {len(ft)} distinct | ecoregions: {len(eco)} distinct")
    out.append("- age class: " + " ".join(f"{k}={ac[k]}({100*ac[k]//n}%)" for k in sorted(ac)))
    out.append("- site class: " + " ".join(f"{k}={sc[k]}({100*sc[k]//n}%)" for k in sorted(sc)))
    out.append("")
out.insert(9, f"TOTAL across the 4 campaign variants: {grand} stands.\n")
_docs = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "docs"))
open(os.path.join(_docs, "fia_pillar1_coverage.md"), "w").write("\n".join(out) + "\n")
print(f"wrote docs/fia_pillar1_coverage.md ({grand} stands across SN/NE/CS/LS)")
