#!/usr/bin/env python3
"""Generate src/variants/teton/dg_coefficients.jl from data/teton/dg_*.csv.
1D -> Float32[sp] (ISMAP -> Int32). 2D -> Float32/Int32[class, sp] (transpose of CSV rows)."""
import csv
D = "data/teton"
def read1d():
    r = list(csv.DictReader(open(f"{D}/dg_1d_coeffs.csv")))
    return {k: [row[k] for row in r] for k in r[0] if k not in ("species_index","code_alpha")}
def read2d(name):
    r = list(csv.DictReader(open(f"{D}/dg_2d_{name}.csv")))
    cols = [c for c in r[0] if len(c) >= 2 and c[0] == "c" and c[1:].isdigit()]
    # matrix[L][sp]  (L = class index, sp = species)
    return [[row[c] for row in r] for c in cols]
one = read1d()
INT1D = {"ismap"}
lines = ["# dg_coefficients.jl (teton) — large-tree DG coefficient arrays (tt/dgf.f DATA).",
         "# GENERATED by tools/teton/gen_dg_jl.py from data/teton/dg_*.csv (count-validated).",
         "# 1D = Float32[sp] (ISMAP Int32); 2D = [class, sp] matching Fortran ARR(L,K). Do not hand-edit.",
         ""]
for k, v in one.items():
    ty = "Int32" if k in INT1D else "Float32"
    vals = ", ".join(str(int(float(x))) for x in v) if k in INT1D else ", ".join(v)
    lines.append(f"const TT_{k.upper()} = {ty}[{vals}]")
lines.append("")
TWO = {"dgfor":"Float32","dgsic":"Float32","dgds":"Float32","dgccfc":"Float32",
       "igccfm":"Int32","ibserv":"Int32","idgsim":"Int32","maploc":"Int32","mapdsq":"Int32"}
for name, ty in TWO.items():
    m = read2d(name)
    lines.append(f"const TT_{name.upper()} = {ty}[")
    for Lrow in m:
        cast = (lambda x: str(int(float(x)))) if ty == "Int32" else (lambda x: x)
        lines.append("    " + " ".join(cast(x) for x in Lrow) + ";")
    lines.append("]")
# specials
dghab = [row["value"] for row in csv.DictReader(open(f"{D}/dg_dghab.csv"))]
lines.append(f"const TT_DGHAB = Float32[{', '.join(dghab)}]")
ich = [row["maphab_base"] for row in csv.DictReader(open(f"{D}/dg_ichbcl.csv"))]
lines.append(f"const TT_ICHBCL = Int32[{', '.join(ich)}]")
lines.append("")
open("src/variants/teton/dg_coefficients.jl","w").write("\n".join(lines))
print(f"wrote src/variants/teton/dg_coefficients.jl ({len(one)} 1D + {len(TWO)} 2D + DGHAB/ICHBCL)")
