#!/usr/bin/env bash
# Active campaign: FVS → FVSjl port. Western variant cluster + all major extensions are DONE.
# Goal: docs/WESTERN_ROLLOUT_GOAL.md ; off-switch: touch docs/WESTERN_ROLLOUT_COMPLETE.
DONE=/workspace/FVSjl/docs/WESTERN_ROLLOUT_COMPLETE
GOAL=/workspace/FVSjl/docs/WESTERN_ROLLOUT_GOAL.md
[ -f "$DONE" ] && exit 0
echo "=== ACTIVE GOAL (Stop hook) — FVS→FVSjl port: post-WRD backlog ===" >&2
cat "$GOAL" >&2
echo "=== DISCIPLINE (unchanged): validate BIT-EXACT-OR-CORNERED vs the LIVE relinked FVS oracle per chunk; MEASURE don't infer (instrument the Fortran, g16 single-.o-swap dump-replay, instrumented .sum byte-identical before trusting); per-record treelist diff INVALID after tripling (use .sum aggregates / pre-split window); reuse the shared engine; never FFI an RNG; commit ONLY validated chunks; verify-by-run on the MERGED tree after every merge; block-on-signal via a foreground-blocking Bash wait (NOT idle stop-hook cycling). ===" >&2
echo "=== STATUS 2026-08-17 (kt-variant-port HEAD e085af59): ALL ~22 US variants + BC growth+volume DONE; FFE/ECON/Climate-FVS/base+spatial-mistletoe(NEWSPRED #196)/ORGANON/DBS/SVS-data-path/WRD(rd/, 15 variants live) DONE. ROADMAP ITEM 1 DMNTRD DONE (#196 fully closed). ROADMAP ITEM 2 insect/pathogen IN PROGRESS: DFB✓ DFTM✓ WPBR✓ (all 3 COMPLETE end-to-end) + LPMPB✓ (deterministic Cole rate-of-loss core bit-exact vs FVSie_lpmpb, seam inert) + WSBWE◐ (BEACHHEAD: BWERAN RNG bit-exact + WSBW reader inert, stand-level oracle FVSem_wsbwe relinks+runs) MERGED; WWPB◐ beachhead only (END-TO-END PPE-BLOCKED — outbreak driver needs the absent PPE landscape harness; DEFERRED, USER decision like #196). ===" >&2
echo "=== NEXT (USER ROADMAP 2026-08-17, work in ORDER): (2, continue) WSBWE DEFOLIATION EFFECT KERNEL — the beachhead is merged; next chunk = IBWSPM per-variant host tables → DEFOL deterministic scheduling on a HEAVY true-fir/spruce host stand (EM S248112 is LP/PP-dominant, no effect) → BWEDAM/BWEDIE growth-loss/top-kill/mortality kernel (dump-replay vs instrumented FVSem_wsbwe) → BWEGO gate seam (gradd.f:108, mirror DFB) → BUDLITE/GENDEFOL stochastic LAST. Recipe: scratchpad/wsbwe/HANDOFF.md. (WWPB is PPE-deferred — do NOT port the PPE harness without a USER decision.) (3) COVER understory covr(11)+vcovr(3)+pg(14). (4) ON (canada/on) Ontario/Penner variant. Insect-model recipe (proven ×5): relink FVS<v>_<model> (variant .o − ex<model>.o no-op + real model .o) → scope→kw(keywds.f opt#)→deterministic-core(g16 dump-replay, instrumented .sum byte-identical)→own MINSTD LCG seed 55329 (never FFI)→effect/mortality→gated simulate.jl seam→.sum-DELTA cornered per #206 straddle. Off-switch (USER's call): touch docs/WESTERN_ROLLOUT_COMPLETE ===" >&2
exit 2
