#!/usr/bin/env bash
# Active campaign: WESTERN FVS variant cluster + extensions rollout (NOT a single variant).
# Goal: docs/WESTERN_ROLLOUT_GOAL.md ; off-switch: touch docs/WESTERN_ROLLOUT_COMPLETE.
DONE=/workspace/FVSjl/docs/WESTERN_ROLLOUT_COMPLETE
GOAL=/workspace/FVSjl/docs/WESTERN_ROLLOUT_GOAL.md
[ -f "$DONE" ] && exit 0
echo "=== ACTIVE GOAL (Stop hook) — Western FVS variant cluster + extensions rollout ===" >&2
cat "$GOAL" >&2
echo "=== DISCIPLINE: validate bit-exact vs LIVE FVS per chunk; MEASURE don't infer; per-record treelist diff INVALID after tripling (use .sum / pre-split); reuse the shared engine. Do NOT stop at one variant. DONE-or-cornered: #140(BM), #137(EM self-thin), EM-sub-inch-DG(crown-dub), #191(TT aspen), #143(IE pvref1 + EM AUTOES re-measured cornered +4-10% TPA, BA/TopHt match), #194(CI esgent birth-cycle fixed, transition cornered), CI-vol(bit-exact @cyc0), Climate-FVS. ★★ 2026-08-12 LATEST (6 commits): UT/TT CROWN-DUB FAMILY fixed — d<1 sub-1\" inventory-seedling DUBSCR (TT#198 862f320 / UT#199 f3edc5b) + d≥1 WOODLAND-CL crown (UT#203 a0e8cee / TT#204 2249737; CI clean) + the BROAD UT double-CRATET-site-conversion bug (12dbc6e, PP DDS now bit-exact, ~5-8% under-growth on all UT RM-site stands). ⚠ CORRECTION: \"WHOLE CLUSTER bit-exact-or-cornered\" holds at CYC0 + LARGE-TREE DG, but MULTI-CYCLE real-FIA carries REAL DETERMINISTIC residuals in SMALL-TREE/WOODLAND/ASPEN regimes the ref stands MASK — OPEN: #206 utt01 real −6.6%@2090 (NOTRIPLE, ref stand!), #205 TT aspen-dominated +30% over-growth (DBH-at-4.5'-crossing; \"#158/#191 resolved\" INCOMPLETE for aspen-dominated). Measure regime-stratified. #196: BC metric-DATABASE units bug FOUND+FIXED (42eb555, cyc0 bit-exact TPA/SDI/TopHt/QMD); REMAINING = YSM multi-cycle under-mortalization ISOLATED to MISSING dwarf mistletoe: DM-free V3 control mrun/all_BC.key shows jl's BC V3 self-thin MATCHES oracle (TPA 2089→1253 vs 2087→1292), so YSM extra mort = the unported NEWSPRED spatial DM (canada/newmist ~50 rtns incl DMAUTO) + BC not in DM dispatch. FIX = port canada/newmist NEWSPRED (~8761 lines/~55 rtns SPATIAL DM, variant-comparable) + wire BC — a MAJOR multi-session port of an OPTIONAL model, niche value (only exercised case = crash-blocked YSM DATABASE), validation A/B crash-blocked ⇒ COST/BENEFIT is a USER decision. base mistoe.f done N-Rockies+CR. + BC V2/non-ICH. Off (USER's call): touch docs/WESTERN_ROLLOUT_COMPLETE ===" >&2
exit 2
