#!/usr/bin/env bash
# Active campaign: FVS → FVSjl port. Western variant cluster + all major extensions are DONE.
# Goal: docs/WESTERN_ROLLOUT_GOAL.md ; off-switch: touch docs/WESTERN_ROLLOUT_COMPLETE.
DONE=/workspace/FVSjl/docs/WESTERN_ROLLOUT_COMPLETE
GOAL=/workspace/FVSjl/docs/WESTERN_ROLLOUT_GOAL.md
[ -f "$DONE" ] && exit 0
echo "=== ACTIVE GOAL (Stop hook) — FVS→FVSjl port: post-WRD backlog ===" >&2
cat "$GOAL" >&2
echo "=== DISCIPLINE (unchanged): validate BIT-EXACT-OR-CORNERED vs the LIVE relinked FVS oracle per chunk; MEASURE don't infer (instrument the Fortran, g16 single-.o-swap dump-replay, instrumented .sum byte-identical before trusting); per-record treelist diff INVALID after tripling (use .sum aggregates / pre-split window); reuse the shared engine; never FFI an RNG; commit ONLY validated chunks; verify-by-run on the MERGED tree after every merge; block-on-signal via a foreground-blocking Bash wait (NOT idle stop-hook cycling). ===" >&2
echo "=== STATUS 2026-08-17 (kt-variant-port HEAD 5a9044e9): ALL ~22 US variants + BC growth+volume DONE; FFE/ECON/Climate-FVS/base+spatial-mistletoe(NEWSPRED #196)/ORGANON/DBS/SVS-data-path/WRD(rd/, 15 variants live) DONE. ROADMAP ITEM 1 DMNTRD DONE (#196 fully closed). ROADMAP ITEM 2 insect/pathogen — 5 of 6 models core-or-fully COMPLETE: DFB✓ DFTM✓ WPBR✓ (full end-to-end) + LPMPB✓ (deterministic Cole core bit-exact, seam inert) + WSBWE✓ (manual-DEFOL LIVE end-to-end: 2000 ΔTPA -476 = oracle -476 bit-exact, cornered by #206); WWPB◐ PPE-BLOCKED (deferred, USER decision). Deferred sub-paths: WSBWE BUDLITE/GENDEFOL(needs weather)+non-EM host variants, LPMPB CURRMORT/RANSTART/LPOPDY. ===" >&2
echo "=== NEXT (USER ROADMAP 2026-08-17, work in ORDER): (3) COVER FUNCTIONALLY COMPLETE for EM — BOTH halves emit bit-exact primary output end-to-end vs FVSem_g16: CANOPY COVER STATISTICS (TREES/COVER/VOLUME bit-exact via CVCW/CVSHAP/CVCBMS/CVSUM + em_cwcalc crown-width 353/353) + SHRUB STATISTICS/CANOPY-AND-SHRUBS-SUMMARY (byte-exact cyc0, cornered by #206 via CVBROW/CVSCON 64+164/CVSUM-shrub/CVCLAS). COVER is REPORT-ONLY (no tree/.sum write, no RNG, active in shipped western binaries — NO relink). Remaining COVER = refinements (CVBCAL calibration; SHRUB-SMALL CONIFER COMPETITION table; post-thin ITHN=2; non-EM habitat raw-code recovery; canopy BIOMASS DDS/DG cyc0-timing; height-imputation) — LOWER priority, primary output already bit-exact. (4) **ON (canada/on) Ontario variant — NOW: own Penner growth model, BC is the only ported Canada variant. Beachhead like the western variants: relink FVSon_clean from bin/FVSon_buildDir/*.o, port the variant-registry seam (variant.jl Ontario + variant_from_code + FVSjl.jl include) + on/dgf.f growth, validate cyc0 large-tree DGF/DDS bit-exact vs FVSon_clean on ont01, then species/site/HTG/vol chunks.** Optionally circle back to deferred insect sub-paths (WSBWE BUDLITE/GENDEFOL, LPMPB CURRMORT/RANSTART/LPOPDY) or COVER refinements. Insect/pathogen recipe (proven ×6): relink FVS<v>_<model> (variant .o − ex<model>.o no-op + real model .o) → kw(keywds.f opt#) → deterministic core (g16 dump-replay, instrumented .sum byte-identical) → own MINSTD LCG seed 55329 (never FFI; route transcendentals via glibc libm ccall for Float32 bit-exactness) → effect/mortality → gated simulate.jl seam (pre-tripling, if !tripled) → end-to-end .sum-DELTA cornered per #206. MEASURE BOTH SIDES per cycle — isolated dump-replay misses glue/feeder bugs (IY(ICYC), IFINT, OLDTPA=TPROB, alpha-species SPDECD all bit us). (WWPB PPE-deferred — do NOT port the PPE harness without a USER decision.) Off-switch (USER's call): touch docs/WESTERN_ROLLOUT_COMPLETE ===" >&2
exit 2
