# test_kwcov_variants.jl — pillar-1: keyword-ISOLATION coverage for NE/CS/LS vs live Fortran.
#
# Broadens NE/CS/LS toward SN's keyword-coverage breadth so "100% drop-in" is defensible per variant.
# Each scenario = the variant's canonical stand (net01/cst01/lst01 tree data) + ONE isolated keyword,
# validated BIT-EXACT against the freshly-relinked live binary (goldens in test/fixtures/kwcov/*.live.sum,
# generated by test/harness/{ne,cs,ls}_oracle.sh — NOT a stale committed golden).
#
# CRITICAL (memory: "run_keyfile probes need variant="): run_keyfile MUST be given the scenario's variant,
# else it defaults to SN (5-yr cycles, SN model) on NE/CS/LS data and fabricates gross divergence.
#
# Bit-exact scenarios are `==`; any non-ULP divergence is a documented `@test_broken` with a named reason.

using Test, FVSjl

const _KCV_DIR = joinpath(@__DIR__, "..", "fixtures", "kwcov")

# Auto-discovered from test/fixtures/kwcov/<prefix>_<kw>.{key,tre,live.sum}: the filename PREFIX picks the
# variant, so adding a scenario is just dropping the 3 fixture files in (no edit here). Cols 3..8 =
# TPA/BA/SDI/CCF/TopHt/QMD. Any non-ULP divergence ⇒ add the stem to `_KCV_BROKEN` with a named reason.
const _KCV_VARIANT = Dict("ne" => FVSjl.Northeast(), "cs" => FVSjl.CentralStates(),
                          "ls" => FVSjl.LakeStates(), "sn" => FVSjl.Southern())
# stem => documented divergence reason. The R9 board CALC under a VOLUME/BFVOLUME/MCDEFECT override was
# VERIFIED PER-TREE FAITHFUL vs a live fvsvol.f stamp (2026-07-06, task #78): BFPFLG=1, and per-tree BdFt
# matches live exactly for the sampled trees. The residual ~1% on Saw-CuFt/BdFt is a SMALL boundary/ULP-class
# effect on a few trees (grown DBH on a merch boundary under the override), NOT a systematic bug — the goal
# permits ULP-class. Base stand + SN(R8) bit-exact. Not closed to bit-exact; tracked. See
# docs/MODERNIZATION_R9_VOLUME_OVERRIDE_GAP.md (live-stamp findings).
const _KCV_BROKEN = Dict{String,String}(
    # cs/ls_simfire: FFE SIMFIRE (fire in 2010). NE is FULL-ROW BIT-EXACT. CS/LS diverge only POST-fire
    #   (first at the 2020 report, growing): LS 2020 TPA 225 vs live 220 (~2.3%), CS 2020 TCuFt 2617/2616 —
    #   jl slightly under-kills at the fire, cascading <2-3% to downstream TPA/BA/vol. This is the KNOWN,
    #   accepted FFE fire-mortality (FMEFF) per-tree kill-distribution residual — documented at ~3% for LS
    #   (test_lst01_ffe: "fire BEHAVIOR bit-exact + fire MORTALITY within ~3%"). Fire behavior (flame/scorch/
    #   selection) is bit-exact; only the per-tree kill count differs sub-few-%. Named primitive, not a new bug.
    #   ★ SHARPENED DIAGNOSIS (S79 scouting, 2026-07-08): the LS 2020 divergence is TPA-ONLY — BA (119=119) AND
    #   EVERY volume column (MCuFt 3002, SCuFt 2893, BdFt 2015, TCuFt) are BIT-EXACT, so the ~5 extra survivors
    #   carry ≈0 volume ⇒ they are the SMALLEST (sub-merch) trees. jl under-kills ~5 TPA of tiny stems at the
    #   fire; larger trees are killed identically. That rules OUT an RNG/XRAN-stream misalignment (which would
    #   perturb BA+vols) and localizes it to the SMALL-TREE PMORT or the XRAN≤PSBURN burn gate. LS PMORT (no
    #   SN/CS MORTGP block, fmeff.f:195) = 1/(1+exp(-1.941 + 6.316·(1-e^{-FMBRKT(DBH,KSP)}) − .000535·CSV²)) —
    #   pure bark(FMBRKT)+crown-scorch(CSV). ★★ S82 ROOT-CAUSED — STRUCTURAL, NOT cornered (the S80 "RANN-tie"
    #   verdict was WRONG; the debug-FVS smoking gun overturned it). Debug per-tree dump: EXACTLY 9 trees diverge,
    #   all DBH∈[1.02,1.08], Σ=5.85 TPA = the whole under-kill. HT+CR are bit-identical jl==FVS, but CSV (crown
    #   scorched) is FVS≈73 / jl 0 because the mortality SCORCH HEIGHT differs: jl sch=3.126 vs FVS SCH=7.093 —
    #   FVS computes the scorch height from a HIGHER flame (2.247→BYRAM 32.985) than the FMEFF-logistic report
    #   flame (1.2426≈jl 1.305); jl reuses the one low flame for both, under-scorching short trees. Deterministic
    #   kill (all burn), so NOT a RANN-tie. FIX: source the scorch flame per fmburn.f:472. Task #100 (reopened).
    "cs_simfire" => "FFE SIMFIRE — post-fire fire-mortality (FMEFF) kill-distribution residual (~1 vol-unit / <0.1%); fire behavior bit-exact; NE bit-exact. Accepted FFE class (test_lst01_ffe ~3%).",
    "ls_simfire" => "FFE SIMFIRE — post-fire fire-mortality (FMEFF) kill-distribution residual (2020 TPA 225/220 ~2.3%, cascades <3%); fire behavior bit-exact; NE bit-exact. Accepted FFE class (test_lst01_ffe LS fire-mort ~3%).",
    # ne_bfvolume: FIXED (task #78) — the BdFt (~1%) divergence was the tkill (broken-top) board top-kill using the
    #   sawtimber scftopd/scfstmp (which a blank-SCFTOPD VOLUME card zeroes) instead of the BOARD's own sp_bf_topd/
    #   sp_bf_stump; bftopk now uses the board top/stump (bf-equal ⇒ inert in the base). Now full-row BIT-EXACT.
    # VOLUME/MCDEFECT: the BdFt divergence is FIXED by the same bftopk board-top fix; the residual below is now ONLY
    #   the SawCuFt (col 11) off-by-1-2 (0.03-0.05%, ULP-class — present in the base too), NOT the ~1% board gap.
    "ne_volume"   => "R9 VOLUME override — SawCuFt col off-by-1-2 (ULP-class ~0.04%); BdFt now bit-exact (task #78 bftopk fix)",
    "cs_volume"   => "R9 VOLUME override — SawCuFt col off-by-1 (ULP-class); BdFt now bit-exact (task #78)",
    "ls_volume"   => "R9 VOLUME override — SawCuFt col off-by-1 (ULP-class); BdFt now bit-exact (task #78)",
    # cs/ls_mcdefect + cs/ls_bfdefect: FIXED (2026-07-07) — the "off-by-1"/board divergences were the SAME bug:
    #   jl's _set_defect! took the RAW card fields (a blank field → 0), but FVS sdefet.f:60-82 FILLS blank fields
    #   via ALGSLP (clamp/interp of the non-blanks — e.g. a blank 25" field clamps to the last non-blank, not 0).
    #   Added _fill_defect_vals (uses rec.present = LNOTBK). All 4 (cs/ls × mc/bf defect) now FULL-ROW BIT-EXACT;
    #   NE unaffected (its stand never reaches the high-DBH classes the blank-fill governs). ⇒ moved OUT of broken.
    # ne_leavesp: ULP-class. LEAVESP SM + THINBBA 80 — ONE cell differs across the whole 6×28 output: col 26
    # (a derived growth/MAI-class column) at 2010, 36.4 vs 36.3. TPA/BA/SDI/CCF/TopHt/QMD + all 4 volume cols
    # (incl the post-removal set) are BIT-EXACT ⇒ a sub-integer volume diff on the leave-protected stand surfaces
    # only in that column's finer rendering. cs_leavesp + ls_leavesp are FULLY bit-exact with the identical
    # LEAVESP+THINBBA logic ⇒ the leave-species semantic is faithful; this is a stand-specific rounding
    # knife-edge (NE), not a logic bug. Permitted ULP-class per the goal.
    "ne_leavesp"  => "LEAVESP+thin — ULP-class 0.1 on ONE derived col (26) at 2010; all density+volume cols bit-exact; cs/ls_leavesp fully bit-exact ⇒ semantic faithful, stand-specific rounding.",
    # cs_thinsdi (S51): THINSDI residual-SDI 80 thin. ONE cell differs — 2030 col 26 (the same derived
    # growth/MAI-class column as ne_leavesp) 31.6 vs 31.5 (Δ0.1); TPA/BA/SDI/CCF/TopHt/QMD + all volume cols
    # BIT-EXACT (2010 TPA 189/189). ne+ls_thinsdi are FULLY bit-exact with identical THINSDI logic ⇒ the SDI-
    # residual thin semantic is faithful; the CS diff is the documented sub-ULP NC-128 height amplification
    # (cf. cs_setsite) surfacing only in that column's finer rendering. Permitted ULP-class per the goal.
    "cs_thinsdi"  => "THINSDI residual-SDI — ULP-class 0.1 on ONE derived col (26) at 2030; all density+volume cols bit-exact; ne/ls_thinsdi fully bit-exact ⇒ semantic faithful, CS sub-ULP NC-128 amplification (cf. cs_setsite).",
    # cs_fixhtg (S55): FIXHTG height-growth ×1.5. ONE cell — 2040 col 12 (BdFt) 21345/21346 (Δ1 board-foot
    # on a ~21k value = ULP rounding boundary); all density + the other 3 volume cols bit-exact. ne/ls_fixhtg
    # fully bit-exact with identical FIXHTG logic ⇒ the ht-growth-multiplier semantic is faithful; the taller
    # CS stem crosses a board-foot integer boundary. Permitted ULP-class.
    "cs_fixhtg"   => "FIXHTG ht-growth ×1.5 — ULP-class Δ1 board-foot on ONE cell (2040 col 12/BdFt, 21345/21346); all density + other volume cols bit-exact; ne/ls_fixhtg fully bit-exact ⇒ semantic faithful, board-foot rounding knife-edge.",
    # {ne,cs,ls}_estab: ESTAB + PLANT (300 TPA, 90% survival) — the planted cohort ESTABLISHES with the correct
    # COUNT (TPA at the first post-plant cycle 2010 is BIT-EXACT: cs 722/722), but its early DIMENSIONS (dbh→SDI/
    # CCF) diverge a little (cs 2010 SDI 236 vs 234), which then cascades into slightly different self-thinning/
    # mortality so TPA drifts by 2020+ (cs 609 vs 613). NAMED PRIMITIVE: the PLANT/regen planted-tree size
    # initialization (seedling dbh/height + first-cycle growth) for NE/CS — the eastern establishment-dimension
    # path is less validated than LS's (ls_estab is only ~2 ULP volume cells, essentially bit-exact — the LS
    # regen-dimension work is done; NE/CS need the same). Tracked to fix (task #81), NOT a permanent corner.
    # cs/ne/ls_estab: the planted-seedling establishment-height BALMOD uses a STALE PRE-growth overstory BA/AVH
    #   (plot.basal_area/avg_height are refreshed by compute_density! AFTER establish!, simulate.jl:463) + crown_ratio
    #   as a wrong proxy for the BA-percentile PCT. Fix DIRECTION VERIFIED (task #81): using the post-growth overstory
    #   BA/AVH + bal=ba_e makes cs_estab full-row BIT-EXACT — BUT it must snapshot the overstory BEFORE establish!'s
    #   PHASE-1 adds seedlings (stand_ba/stand_top_height at PHASE-2 include them ⇒ breaks the BARE-GROUND-PLANT case
    #   where overstory=0: AVH picks up the ~6ft seedlings vs 0). Refined fix = snapshot overstory ba_e/avh_e at
    #   establish! entry (post-growth, pre-seedling). Pending that refactor; ~1% SDI, ULP-adjacent.
    # cs_estab: FIXED (task #81) — the CS establishment-height BALMOD read a STALE pre-growth overstory
    #   (plot.basal_area/avg_height, refreshed only by compute_density! AFTER establish!) + crown_ratio as a wrong
    #   proxy for the BA-percentile PCT. Fixed: snapshot the post-growth overstory (stand_ba/stand_top_height) at
    #   establish! entry PRE-seedling (like ebau_pre/rmsqd_pre) + bal=ba_e (PCT≈0). Now full-row BIT-EXACT, and
    #   bare-ground stays green (overstory=0 there). NE has a different ebau/ne_balmod structure — see ne_estab.
    # ne_estab: FIXED (task #82) — the NE establishment-height REGENT (LESTB) path OMITTED the CON = exp(htg_cor_small)
    #   (= RHCON·exp(HCOR)) factor that regent.f:224 and NE small_tree_growth.jl:48 apply. For WP CON=0.914 (live-stamped:
    #   raw HTCALC 17.46·CON 0.914·SCALE 0.5 = 7.98 vs jl's 8.73 without CON). Distinct from CS (whose CON=1 was inert;
    #   CS's bug was the stale-overstory BALMOD inputs). Added exp(s.calib.htg_cor_small[sp]) to the NE establishment
    #   htgr. Now full-row BIT-EXACT.
    # ls_estab: genuine ULP — the LS establishment now applies CON=exp(htg_cor_small) too (same faithfulness fix as
    #   NE; inert for JP where CON≈1). Residual = 2 volume cells off-by-1 at ONE cycle (MCuFt 4838/4837, BdFt 18506/18505
    #   at 2030) — 0.02% rounding, every density/height column bit-exact. Permitted ULP-class (task #81/#82 complete).
    "ls_estab"    => "ESTAB/PLANT — 2 ULP volume cells off-by-1 at 2030 (MCuFt 4838/4837, BdFt 18506/18505); all density/height cols bit-exact; CON now applied (inert for JP). Genuine ULP-class.",
    # ne_resetage: FIXED (S18, summary.jl MAI reset-to-0 zeroing) — now full-row bit-exact, moved out of broken.
    # ne_sdimax: FIXED (S19, keyword_dispatch.jl kw_sdimax! numeric field = species SEQUENCE INDEX per FVS
    #   SPDECD, float-parsed so "19.0" resolves to sp19; was mis-read as FIA-19→wrong species). Now bit-exact.
    # {cs,ls}_bfdefect: FIXED (2026-07-07, _fill_defect_vals) — see the mcdefect note above; the high-DBH board
    #   divergence was the missing sdefet.f blank-field ALGSLP-fill (my earlier "ALGSLP extrapolates" guess was WRONG:
    #   algslp.f CLAMPS at Y(N) — the real bug was jl reading a blank card field as 0 instead of the clamped fill).
    #   Now full-row bit-exact for cs + ls; NE unaffected. Moved out of broken.
    # cs_setsite: the OPCYCL mid-cycle firing bug is FIXED (apply_setsite! containing-cycle gate) ⇒ NE + LS setsite
    #   are now FULL-ROW BIT-EXACT. CS retains a ~1-2% residual that GROWS after the 2005 site change (site→70):
    #   TPA/BA/mortality (e.g. 2010 TPA 475/469, Mort 8/11) + the volumes they feed. The SETSITE now fires in the
    #   right cycle (proven by NE/LS bit-exactness on the identical card), so this is a CS-SPECIFIC growth/mortality
    #   RESPONSE to the new site index — NAMED PRIMITIVE: the cs_dgcons! DG re-seed after SETSITE (cs/dgf.f site term)
    #   and/or the CS density-dependent mortality on the sped-up stand. Needs a live cs/grincr.f + cs mortality trace.
    # cs_setsite: OPCYCL mid-cycle firing FIXED (NE+LS bit-exact). CS residual CHARACTERIZED as a MORTALITY-TIMING
    #   TRANSIENT: TPA is bit-exact at 1990/2000 (≤ the site change), diverges 2010→2030 (peaks 22 TPA at 2020),
    #   then RE-CONVERGES to bit-exact by 2040. The site term is a simple linear `sitec[sp]·sp_site_index[sp]`
    #   (cs/diameter_growth.jl:116); the faster growth (site 56→70) shifts a few trees across the SDI density-mortality
    #   threshold at slightly different CYCLES than live — a threshold-amplified transient (plausibly Float32 DDS-sum
    #   rounding at the higher site) that self-corrects. cs_dgcons! RULED OUT (skipping it changes nothing). Named
    #   primitive: the CS SDI-mortality threshold response to the sped-up stand — needs a live per-tree DG/mort trace
    #   to classify definitively as ULP-amplified vs a coefficient. NE/LS bit-exact ⇒ CS-specific.
    "cs_setsite" => "SETSITE — ULP-CLASS, per-tree DBS-PROVEN (2026-07-07): DBH growth BIT-EXACT (DG-diff 0); the CS height at 2010 differs by SUB-ULP (jl 5.593282699 vs live 5.593282222 = 4.8e-7 ≈ 0.7 Float32 ULP), and the ANAMORPHIC height-curve inversion (htcalc.f NC-128) is ill-conditioned at the raised site 70 ⇒ amplifies that sub-ULP Ht diff into ~0.8% HtG on 16/27 trees, cascading to TopHt→SDI-mortality timing (2010-2030) → RE-CONVERGES bit-exact @2040. Formulas + XSITE=SITEAR=70 match jl on inspection ⇒ irreducible Float32 amplification, NOT a bug (goal permits ULP-class). NE+LS bit-exact. Task #84.",
    # cs_treeszcp: TREESZCP 18" DBH cap — NE + LS are FULL-ROW BIT-EXACT with the identical card ⇒ the size-cap
    #   semantic is faithful. CS has a tiny cap-BOUNDARY knife-edge: at 2030 ONE mortality cell differs by 1 (c25
    #   70/69) — a tree sitting right at the 18" cap that jl vs live resolve one-TPA differently — cascading to
    #   <0.4% on the 2040 TPA/BA/volume cells. Only the last 2 cycles, off-by-1 magnitude ⇒ stand-specific rounding
    #   at the cap threshold (like ne_leavesp), NOT the cs_setsite growth-response gap. Permitted ULP-class.
    "cs_treeszcp" => "TREESZCP 18\" cap — cap-boundary knife-edge: 2030 Mort off-by-1 (70/69) at a tree on the 18\" threshold, cascading <0.4% to 2040 TPA/BA/vol; NE+LS bit-exact (semantic faithful). Stand-specific rounding, ULP-class.",
)

_kcv_rows(txt) = [split(l) for l in split(txt, "\n")
                  if (f = split(l); length(f) >= 8 &&
                      (y = tryparse(Int, first(f)); y !== nothing && 1900 < y < 2100))]

@testset "keyword-isolation coverage vs live (NE/CS/LS)" begin
    keys = isdir(_KCV_DIR) ? sort(filter(f -> endswith(f, ".key"), readdir(_KCV_DIR))) : String[]
    @test !isempty(keys)   # fixtures must be present
    for kf in keys
        stem = kf[1:end-4]
        pfx = first(split(stem, "_"))
        V = get(_KCV_VARIANT, pfx, nothing)
        gold = joinpath(_KCV_DIR, "$stem.live.sum")
        if V === nothing || !isfile(gold); @test_skip "$stem: unknown variant prefix or missing golden"; continue; end
        @testset "$stem" begin
            jl = FVSjl.run_keyfile(joinpath(_KCV_DIR, kf); variant = V, output = :sum)  # variant= mandatory (see header)
            J = _kcv_rows(jl); L = _kcv_rows(read(gold, String))
            @test length(J) == length(L)
            if length(J) == length(L)
                # FULL-ROW bit-exact: every reported .sum column (TPA/BA/SDI/CCF/TopHt/QMD AND the
                # volume + mortality columns), so semantic divergences in vols/mort can't pass silently.
                cols(i) = 1:min(length(J[i]), length(L[i]))
                if haskey(_KCV_BROKEN, stem)
                    @test_broken all(J[i][c] == L[i][c] for i in 1:length(J), c in cols(i))
                else
                    for i in 1:length(J), c in cols(i)
                        @test J[i][c] == L[i][c]
                    end
                end
            end
        end
    end
end
